package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import java.util.Optional;
import java.util.function.Supplier;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModule;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;

import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.filter.SlewRateLimiter;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.units.measure.Distance;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.shuffleboard.Shuffleboard;
import edu.wpi.first.wpilibj.shuffleboard.ShuffleboardTab;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;

import edu.wpi.first.wpilibj2.command.button.CommandXboxController;
import frc.robot.Constants;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    /** Shuffleboard tab for vision alignment debugging */
    private final ShuffleboardTab visionAlignTab;

    /** Vision subsystem for translation override during auto */
    private VisionSubsystem m_visionSubsystem = null;

    /** Flag to enable/disable vision translation override during auto (tracks AprilTag 11) */
    private boolean m_visionRotationOverrideEnabled = false;

    /** Swerve request to apply during robot-centric path following */
    private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds = new SwerveRequest.ApplyRobotSpeeds();

    /** Swerve request for teleoperated driving */
    private final SwerveRequest.FieldCentric teleopRequest = new SwerveRequest.FieldCentric()
        .withDeadband(Constants.DriveConstants.maxSpeed * 0.1)
        .withRotationalDeadband(Constants.DriveConstants.maxAngularRate * 0.1)
        .withDriveRequestType(DriveRequestType.OpenLoopVoltage);

    /** Swerve request for alignment (no rotation deadband) */
    private final SwerveRequest.FieldCentric alignRequest = new SwerveRequest.FieldCentric()
        .withDeadband(Constants.DriveConstants.maxSpeed * 0.1)
        .withDriveRequestType(DriveRequestType.OpenLoopVoltage);

    /** Aim mode: field-centric so left stick stays consistent while auto-rotating */
    private final SwerveRequest.FieldCentric aimFieldCentric = new SwerveRequest.FieldCentric()
        .withDeadband(0.0)
        .withRotationalDeadband(0.0)
        .withDriveRequestType(DriveRequestType.OpenLoopVoltage);

    /** Vision alignment tuning parameters */
    private static final double kAimKp = 6.0;            // (rad/s) per rad of tx error - increased for faster tracking
    private static final double kTxDeadbandDeg = 0.5;    // ignore tiny noise - reduced to keep tracking
    private static final double kMinAimRate = 0.3;       // rad/s to overcome stiction (0 to disable)

    /** Smooth rotation so it doesn't snap/jitter */
    private final SlewRateLimiter aimRotLimiter = new SlewRateLimiter(10.0); // rad/s^2

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> setControl(m_translationCharacterization.withVolts(output)),
            null,
            this
        )
    );

    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(7), // Use dynamic voltage of 7 V
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdSteer_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            volts -> setControl(m_steerCharacterization.withVolts(volts)),
            null,
            this
        )
    );

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
     */
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
        new SysIdRoutine.Config(
            /* This is in radians per second², but SysId only supports "volts per second" */
            Volts.of(Math.PI / 6).per(Second),
            /* This is in radians per second, but SysId only supports "volts" */
            Volts.of(Math.PI),
            null, // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdRotation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> {
                /* output is actually radians per second, but SysId only supports "volts" */
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                /* also log the requested output for SysId */
                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
            },
            null,
            this
        )
    );

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        visionAlignTab = Shuffleboard.getTab("Vision Align");
        setupVisionAlignTab();
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        visionAlignTab = Shuffleboard.getTab("Vision Align");
        setupVisionAlignTab();
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        visionAlignTab = Shuffleboard.getTab("Vision Align");
        setupVisionAlignTab();
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    private void setupVisionAlignTab() {
        // Left column - Vision data
        visionAlignTab.addBoolean("Has Target", () -> SmartDashboard.getBoolean("Aim/hasTarget", false))
            .withPosition(0, 0).withSize(2, 1);
        visionAlignTab.addNumber("TX (deg)", () -> SmartDashboard.getNumber("Aim/txDeg", 0.0))
            .withPosition(0, 1).withSize(2, 1);
        visionAlignTab.addNumber("Rot Cmd Raw", () -> SmartDashboard.getNumber("Aim/rotCmdRaw", 0.0))
            .withPosition(0, 2).withSize(2, 1);
        visionAlignTab.addNumber("Rot Cmd Final", () -> SmartDashboard.getNumber("Aim/rotCmdFinal", 0.0))
            .withPosition(0, 3).withSize(2, 1);

        // Right column - Driver inputs
        visionAlignTab.addBoolean("Driver Rotating", () -> SmartDashboard.getBoolean("Aim/driverRotating", false))
            .withPosition(2, 0).withSize(2, 1);
        visionAlignTab.addNumber("VX", () -> SmartDashboard.getNumber("Aim/vx", 0.0))
            .withPosition(2, 1).withSize(2, 1);
        visionAlignTab.addNumber("VY", () -> SmartDashboard.getNumber("Aim/vy", 0.0))
            .withPosition(2, 2).withSize(2, 1);

        // Bottom row - Command status
        visionAlignTab.addBoolean("Command Running", () -> SmartDashboard.getBoolean("Aim/commandRunning", false))
            .withPosition(0, 4).withSize(2, 1);
        visionAlignTab.addNumber("Left Trigger", () -> SmartDashboard.getNumber("Aim/leftTrigger", 0.0))
            .withPosition(2, 3).withSize(2, 1);
    }

    private void configureAutoBuilder() {
        try {
            var config = RobotConfig.fromGUISettings();
            AutoBuilder.configure(
                () -> getState().Pose,   // Supplier of current robot pose
                this::resetPose,         // Consumer for seeding pose against auto
                () -> getState().Speeds, // Supplier of current robot speeds
                // Consumer of ChassisSpeeds and feedforwards to drive the robot
                (speeds, feedforwards) -> {
                    // Apply vision translation override if enabled (tracks AprilTag 11)
                    ChassisSpeeds finalSpeeds = speeds;

                    // Only apply vision override when PathPlanner is commanding movement
                    // This prevents vision from fighting path endpoint/stopping behavior
                    double pathSpeed = Math.hypot(speeds.vxMetersPerSecond, speeds.vyMetersPerSecond);
                    boolean pathIsMoving = pathSpeed > 0.1; // 0.1 m/s threshold

                    if (m_visionRotationOverrideEnabled && m_visionSubsystem != null &&
                        m_visionSubsystem.hasValidTarget() &&
                        pathIsMoving) {  // Only override when path wants movement
                        // Note: Tracking any AprilTag, not just ID 11

                        double tx = m_visionSubsystem.getTargetTX();  // Horizontal offset (degrees)
                        double ty = m_visionSubsystem.getTargetTY();  // Vertical offset (degrees)

                        // Control gains for vision-based translation
                        double kTxToStrafe = 0.015;  // Strafe gain (m/s per degree of TX)
                        double kTyToForward = 0.015; // Forward gain (m/s per degree of TY)

                        // Deadband to avoid jitter when centered
                        double txDeadband = 2.0; // degrees
                        double tyDeadband = 2.0; // degrees

                        // Calculate translation commands based on target offset
                        // TX: positive = target to right, we want to strafe right
                        // TY: positive = target above crosshair, we're too far, back up
                        double strafeCmd = Math.abs(tx) > txDeadband ? tx * kTxToStrafe : 0.0;
                        double forwardCmd = Math.abs(ty) > tyDeadband ? -ty * kTyToForward : 0.0;

                        // Blend vision commands with path commands (not full override)
                        double blendFactor = 0.5; // 50% vision, 50% path
                        finalSpeeds = new ChassisSpeeds(
                            speeds.vxMetersPerSecond * (1 - blendFactor) + forwardCmd * blendFactor,
                            speeds.vyMetersPerSecond * (1 - blendFactor) + strafeCmd * blendFactor,
                            speeds.omegaRadiansPerSecond  // Keep PathPlanner's rotation
                        );

                        SmartDashboard.putBoolean("Auto/VisionOverrideActive", true);
                        SmartDashboard.putNumber("Auto/VisionTX", tx);
                        SmartDashboard.putNumber("Auto/VisionTY", ty);
                        SmartDashboard.putNumber("Auto/VisionStrafeCmd", strafeCmd);
                        SmartDashboard.putNumber("Auto/VisionForwardCmd", forwardCmd);
                        SmartDashboard.putNumber("Auto/TagID", m_visionSubsystem.getTagID());
                        SmartDashboard.putNumber("Auto/PathSpeed", pathSpeed);
                    } else {
                        SmartDashboard.putBoolean("Auto/VisionOverrideActive", false);
                    }

                    setControl(
                        m_pathApplyRobotSpeeds.withSpeeds(ChassisSpeeds.discretize(finalSpeeds, 0.020))
                            .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                            .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())
                    );
                },
                new PPHolonomicDriveController(
                    // PID constants for translation
                    new PIDConstants(10, 0, 0),
                    // PID constants for rotation
                    new PIDConstants(7, 0, 0)
                ),
                config,
                // Assume the path needs to be flipped for Red vs Blue, this is normally the case
                () -> DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red,
                this // Subsystem for requirements
            );
        } catch (Exception ex) {
            DriverStation.reportError("Failed to load PathPlanner config and configure AutoBuilder", ex.getStackTrace());
        }
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            });
        }
    }

    /**
     * Command for teleoperated driving with field-centric control.
     *
     * @param controller The Xbox controller for driver input
     * @return Command to run teleoperated driving
     */
    public Command teleopDrive(CommandXboxController controller) {
        return applyRequest(() ->
            teleopRequest.withVelocityX(-controller.getLeftY() * Constants.DriveConstants.maxSpeed)
                .withVelocityY(-controller.getLeftX() * Constants.DriveConstants.maxSpeed)
                .withRotationalRate(-controller.getRightX() * Constants.DriveConstants.maxAngularRate)
        );
    }

    /**
     * Command for hub-aligned driving. Automatically rotates to face the hub while
     * allowing manual XY translation control.
     *
     * @param controller The Xbox controller for driver input
     * @return Command to run hub-aligned driving
     */
    public Command alignDrive(CommandXboxController controller) {
        return applyRequest(() -> {
            Pose2d drivePose = getState().Pose;
            double centerToShooterMeters = -Constants.DriveConstants.shooterSideOffset.in(Meters);
            Pose2d hubPose = Constants.DriveConstants.getHubPose().toPose2d();
            double centerToHubMeters = drivePose.getTranslation().getDistance(hubPose.getTranslation());
            double shooterToCenterToHubAngleRads = Math.acos(centerToShooterMeters / centerToHubMeters);
            Rotation2d shooterToCenterToHubAngle = Rotation2d.fromRadians(shooterToCenterToHubAngleRads);
            Rotation2d offsetFromHubDesiredAngle = Rotation2d.kCCW_90deg.minus(shooterToCenterToHubAngle);
            Rotation2d desiredCenterAngleFieldRelative = offsetFromHubDesiredAngle.plus(
                drivePose.relativeTo(hubPose).getTranslation().getAngle()
            );
            Rotation2d currentAngle = drivePose.getRotation();
            double rotationalRate = Constants.DriveConstants.rotationController.calculate(
                currentAngle.getRadians(),
                desiredCenterAngleFieldRelative.plus(Rotation2d.k180deg).getRadians()
            );

            return alignRequest.withVelocityX(-controller.getLeftY() * Constants.DriveConstants.maxSpeed)
                .withVelocityY(-controller.getLeftX() * Constants.DriveConstants.maxSpeed)
                .withRotationalRate(rotationalRate * Constants.DriveConstants.maxAngularRate);
        });
    }

    /**
     * Command for vision-aligned driving. Uses Limelight to automatically rotate
     * toward AprilTag while allowing manual XY translation control.
     * Uses FIELD-CENTRIC control so translation stays consistent while rotating.
     *
     * @param controller The Xbox controller for driver input
     * @param visionSubsystem The vision subsystem for AprilTag tracking
     * @return Command to run vision-aligned driving
     */
    public Command visionAlignDrive(CommandXboxController controller, VisionSubsystem visionSubsystem) {
        return applyRequest(() -> {
            // Mark command as running
            SmartDashboard.putBoolean("Aim/commandRunning", true);
            SmartDashboard.putNumber("Aim/leftTrigger", controller.getLeftTriggerAxis());

            // Driver translation (FIELD-CENTRIC so left stick stays consistent while aiming)
            double xCmd = -controller.getLeftY();
            double yCmd = -controller.getLeftX();

            xCmd = MathUtil.applyDeadband(xCmd, 0.08);
            yCmd = MathUtil.applyDeadband(yCmd, 0.08);

            double vx = xCmd * Constants.DriveConstants.maxSpeed;
            double vy = yCmd * Constants.DriveConstants.maxSpeed;

            // Optional manual rotation override (right stick wins if moved)
            double rightX = MathUtil.applyDeadband(controller.getRightX(), 0.12);
            boolean driverRotating = Math.abs(rightX) > 0.0;
            double manualRot = -rightX * Constants.DriveConstants.maxAngularRate;

            double rotCmd = driverRotating ? manualRot : 0.0;

            boolean hasTarget = visionSubsystem.hasValidTarget();
            double txDeg = visionSubsystem.getTargetTX();

            if (!driverRotating && hasTarget) {
                if (Math.abs(txDeg) > kTxDeadbandDeg) {
                    // tx is degrees; convert to radians for sane tuning
                    double txRad = Math.toRadians(txDeg);

                    // Limelight: +tx means target is right. WPILib: +omega is CCW.
                    // To rotate toward a target on the right, you typically need CW => negative omega.
                    rotCmd = -kAimKp * txRad;

                    rotCmd = MathUtil.clamp(
                        rotCmd,
                        -Constants.DriveConstants.maxAngularRate,
                        Constants.DriveConstants.maxAngularRate
                    );

                    if (kMinAimRate > 0.0 && Math.abs(rotCmd) < kMinAimRate) {
                        rotCmd = Math.copySign(kMinAimRate, rotCmd);
                    }
                } else {
                    rotCmd = 0.0;
                }
            }

            double rotCmdBeforeLimiter = rotCmd;
            rotCmd = aimRotLimiter.calculate(rotCmd);

            // Publish comprehensive tuning data to SmartDashboard
            SmartDashboard.putNumber("Aim/txDeg", visionSubsystem.getTargetTX());
            SmartDashboard.putNumber("Aim/rotCmdRaw", rotCmdBeforeLimiter);
            SmartDashboard.putNumber("Aim/rotCmdFinal", rotCmd);
            SmartDashboard.putBoolean("Aim/hasTarget", visionSubsystem.hasValidTarget());
            SmartDashboard.putBoolean("Aim/driverRotating", driverRotating);
            SmartDashboard.putNumber("Aim/vx", vx);
            SmartDashboard.putNumber("Aim/vy", vy);

            return aimFieldCentric
                .withVelocityX(vx)
                .withVelocityY(vy)
                .withRotationalRate(rotCmd);
        });
    }

    /**
     * Resets the aim rotation slew rate limiter.
     * Call this when starting/ending vision alignment to prevent lag or leftover ramp.
     */
    public void resetAimLimiter() {
        aimRotLimiter.reset(0.0);
    }

    /**
     * Sets the vision subsystem to use for translation override during auto.
     * Must be called before enabling vision translation override.
     *
     * @param visionSubsystem The vision subsystem instance
     */
    public void setVisionSubsystem(VisionSubsystem visionSubsystem) {
        m_visionSubsystem = visionSubsystem;
    }

    /**
     * Enables vision translation override during autonomous path following.
     * When enabled, the robot will track AprilTag 11 and override translation
     * (forward/backward and strafe) to center on the tag.
     * PathPlanner still controls rotation according to the path.
     */
    public void enableVisionRotationOverride() {
        m_visionRotationOverrideEnabled = true;
        SmartDashboard.putBoolean("Auto/VisionTrackingEnabled", true);
    }

    /**
     * Disables vision translation override during autonomous path following.
     * The robot will use PathPlanner's translation and rotation targets.
     */
    public void disableVisionRotationOverride() {
        m_visionRotationOverrideEnabled = false;
        SmartDashboard.putBoolean("Auto/VisionTrackingEnabled", false);
    }

    /**
     * Calculates the distance from the shooter position to the hub.
     * Uses the shooter offset and robot pose to determine accurate shooting distance.
     *
     * @return Distance from shooter to hub in meters
     */
    public Distance getShotDistance() {
        Pose2d drivePose = getState().Pose;
        Pose2d hubPose = Constants.DriveConstants.getHubPose().toPose2d();
        double centerToHubMeters = drivePose.getTranslation().getDistance(hubPose.getTranslation());
        double centerToShooterMeters = Constants.DriveConstants.shooterSideOffset.in(Meters);
        double shooterIdealToHubMeters = Math.sqrt(
            Math.pow(centerToHubMeters, 2.0) - Math.pow(centerToShooterMeters, 2.0)
        );
        return Meters.of(shooterIdealToHubMeters);
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }
}